---
title: "Liste d'accomplissements"
author: "Guillaume Guénard, Ph. D. Biologie"
date: 'Compilation: `r format(Sys.time(), "%Y-%m-%d")`'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(yaml)
library(magrittr)

enumerate <- function(x, and = " & ") {
  if(length(x) == 1L) {
    x
  } else {
    y <- rep("", length(x))
    y[length(y) - 1L] <- and
    if(length(y) > 2L) y[1L:(length(y)-2L)] <- ", "
    paste(paste(x,y,sep=""),collapse="")
  }
}

lang <- "fr"

"../CVcontents.yml" %>%
  yaml.load_file -> contents
```

**Adresse:** 2243 rue du Coteau, Saint-Lin-Laurentides QC, J5M 1Z9, Canada,
(514) 707-9569

---

# Articles dans des revues scientifiques avec comité de lecture

```{r, echo = FALSE, results='asis'}
contents$achievement$prja %>%
  lapply(
    function(x) {
      cat(
        "- ",
        enumerate(x$authors), " ",
        x$year,". _",
        x$title,"_ ",
        x$outlet," ",
        x$number,"(",x$issue,")",
        if(!is.null(x$page)) paste(":",x$page) else " ",
        " doi: [",x$doi,"](https://doi.org/",x$doi,")",
        "\n\n",
        sep=""
      )
    }
  ) %>% invisible
```

---

# Présentations de symposium

```{r, echo = FALSE, results='asis'}
contents$achievement$presentation %>%
  lapply(
    function(x, lang) {
      cat(
        "- ",
        enumerate(x$authors), " ",
        x$year,". _",
        x$title,"_ ",
        x$event," -- ",
        x$place[[lang]],
        "\n\n",
        sep=""
      )
    },
    lang = lang
  ) %>% invisible
```

---

# Rapports de recherche

```{r, echo = FALSE, results='asis'}
contents$achievement$report %>%
  lapply(
    function(x, lang) {
      cat(
        "- ",
        enumerate(x$authors), " ",
        x$year,". ",
        x$title[[lang]]," ", x$series[[lang]], ". ",
        if(!is.null(x$number)) paste(" ", x$number, ". ", sep="") else ". ",
        x$place[[lang]], ". ",
        x$page, if(!is.null(x$url)) " [LIEN](",x$url,")",
        "\n\n",
        sep=""
      )
    },
    lang = lang
  ) %>% invisible
## contents$achievement$report[[2L]] -> x
```

---

# Développement de logiciel

```{r, echo = FALSE, results='asis'}
contents$achievement$software %>%
  lapply(
    function(x, lang) {
      cat(
        "[",x$name,"](",x$url,")\n: ",
        enumerate(x$authors), " ",
        x$year,". ",
        x$title," Description: ", x$description, " ", x$version,
        "\n\n",
        sep=""
      )
    },
    lang = lang
  ) %>% invisible
```

---

# Travaux en cours (liste abrégée)

```{r, echo = FALSE, results='asis'}
contents$anticipated %>%
  lapply(
    function(x, lang) {
      cat(
        "- ", enumerate(x$authors), " _",
        x$title, "_ [",x$type,"]",
        "\n\n",
        sep=""
      )
    },
    lang = lang
  ) %>% invisible
```

---
